def _get_url(id: str, color: str) -> str:
    return f"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/{id}&color=%23{color}&inverse=false&auto_play=false&show_user=false&show_artwork=false&show_playcount=false"


MIXES = [
    {"url": _get_url(m["id"], m["color"]), **m}
    for m in [
        {
            "id": "1653656613",
            "color": "36341e",
            "name": "spooky town III",
            "date": "Oct. 31 2023",
            "image_url": "/static/images/spooky_town_iii.jpeg",
            "tags": ["spooky", "halloween", "house", "techno"],
        },
        {
            "id": "1546245496",
            "color": "80902c",
            "name": "afternoon underexertion",
            "date": "Jun. 19 2023",
            "image_url": "/static/images/afternoon_under_exertion.jpeg",
            "tags": ["autumn", "relax", "house"],
        },
        {
            "id": "1503987556",
            "color": "f7ed46",
            "name": "silly season",
            "date": "May 1 2023",
            "image_url": "/static/images/silly_season.jpeg",
            "tags": ["funk", "sunshine", "silly", "house"],
        },
        {
            "id": "1455510700",
            "color": "ff5500",
            "name": "fled's fifty",
            "date": "Feb. 24 2023",
            "image_url": "/static/images/fleds_fifty.jpeg",
            "tags": ["jazz", "hip-hop", "downtempo", "funk"],
        },
        {
            "id": "1372314436",
            "color": "747474",
            "name": "return 2 spooky town",
            "date": "Oct. 31 2022",
            "image_url": "/static/images/return_2_spooky_town.jpeg",
            "tags": ["spooky", "halloween", "house", "techno"],
        },
        {
            "id": "1367528887",
            "color": "847850",
            "name": "slow your circulation",
            "date": "Oct. 21 2022",
            "image_url": "/static/images/slow_your_circulation.jpeg",
            "tags": ["float", "dub", "jazz", "downtempo", "blues"],
        },
        {
            "id": "1351140745",
            "color": "4592dd",
            "name": "bavarian bluebird",
            "date": "Mar. 26 2022",
            "image_url": "/static/images/bavarian_bluebird.jpeg",
            "tags": ["sunshine", "electronic", "house"],
        },
        {
            "id": "1351081432",
            "color": "b93026",
            "name": "BER —> AKL",
            "date": "Dec. 05 2021",
            "image_url": "/static/images/ber_to_akl.jpeg",
            "tags": ["dnb", "bass", "winter", "summer"],
        },
        {
            "id": "1350657289",
            "color": "a43abd",
            "name": "spooky town",
            "date": "Oct. 31 2021",
            "image_url": "/static/images/spooky_town.jpeg",
            "tags": ["spooky", "halloween", "house", "techno"],
        },
        {
            "id": "1350632086",
            "color": "c49736",
            "name": "outta tune E string",
            "date": "Sep. 11 2021",
            "image_url": "/static/images/outta_tune_e_string.jpeg",
            "tags": ["jazz", "downtempo", "hip-hop", "krautrock"],
        },
        {
            "id": "1350626644",
            "color": "eeba9f",
            "name": "schnelltest sommer",
            "date": "Jun. 05 2021",
            "image_url": "/static/images/schnelltest_sommer.jpeg",
            "tags": ["dnb", "jungle", "summer"],
        },
        {
            "id": "1350598885",
            "color": "7b2522",
            "name": "rollin' round the ringbahn",
            "date": "Apr. 19 2021",
            "image_url": "/static/images/rollin_round_the_ringbahn.jpeg",
            "tags": ["dnb", "dark", "rollers"],
        },
        {
            "id": "1350594688",
            "color": "93ddfc",
            "name": "bookworm [CXVIII — CXXXV]",
            "date": "Apr. 05 2021",
            "image_url": "/static/images/bookworm.jpeg",
            "tags": ["house", "deep", "float", "relax"],
        },
        {
            "id": "1350568123",
            "color": "c27574",
            "name": "an ode to mohei",
            "date": "Jan. 22 2021",
            "image_url": "/static/images/an_ode_to_mohei.jpeg",
            "tags": ["farm", "summer", "northland", "nz"],
        },
        {
            "id": "1350265321",
            "color": "91a4ee",
            "name": "the fishing beach",
            "date": "Aug. 13 2020",
            "image_url": "/static/images/the_fishing_beach.jpeg",
            "tags": ["electronic", "float", "relax", "nz"],
        },
        {
            "id": "1349712022",
            "color": "a1a9b7",
            "name": "rain over the bay",
            "date": "May. 06 2020",
            "image_url": "/static/images/rain_over_the_bay.jpeg",
            "tags": ["rain", "peace"],
        },
    ]
]
